### SPAM FILTER

In [5]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

viagra_spam = {'viagra': [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
               'spam': [1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]}

df = pd.DataFrame(viagra_spam)
np_data = df.values

In [6]:
df

viagra  spam
0        1     1
1        0     0
2        0     0
3        0     0
4        0     0
5        0     0
6        0     1
7        0     0
8        1     1
9        1     0
10       1     0
11       0     0
12       0     0
13       1     0
14       0     0
15       0     0
16       0     0
17       0     1
18       0     1
19       1     1

In [7]:
sum((np_data[:, 0] == 1) & (np_data[:, 1] == 1)) / 20

0.15

In [8]:
p_viagra = sum(np_data[:, 0] == 1) / len(np_data)
p_viagra

0.3

In [10]:
p_spam = sum(np_data[:, 1] == 1) / len(np_data)
p_spam

0.3

In [11]:
p_v_cap_s = sum((np_data[:, 0] == 1) & (np_data[:, 1] == 1)) / len(np_data)

In [12]:
p_n_v_cap_s = sum((np_data[:, 0] == 0) & (np_data[:, 1] == 1)) / len(np_data)
p_n_v_cap_s

0.15

In [13]:
p_spam * (p_v_cap_s / p_spam) / p_viagra

0.5

In [14]:
p_spam * (p_n_v_cap_s / p_spam) / (1-p_viagra)

0.2142857142857143

### NAIVE BAYESIAN CLASSIFIER

In [19]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

data_url = '../datasets/ch11/fraud.csv'
df = pd.read_csv(data_url, sep=',')
df.head()

ID  History CoApplicant Accommodation  Fraud
0   1  current        none           own   True
1   2     paid        none           own  False
2   3     paid        none           own  False
3   4     paid   guarantor          rent   True
4   5  arrears        none           own  False

In [20]:
df

ID  History  CoApplicant Accommodation  Fraud
0    1  current         none           own   True
1    2     paid         none           own  False
2    3     paid         none           own  False
3    4     paid    guarantor          rent   True
4    5  arrears         none           own  False
5    6  arrears         none           own   True
6    7  current         none           own  False
7    8  arrears         none           own  False
8    9  current         none          rent  False
9   10     none         none           own   True
10  11  current  coapplicant           own  False
11  12  current         none           own   True
12  13  current         none          rent   True
13  14     paid         none           own  False
14  15  arrears         none           own  False
15  16  current         none           own  False
16  17  arrears  coapplicant          rent  False
17  18  arrears         none          free  False
18  19  arrears         none           own  False
19  20     paid         none           own  False

In [21]:
del df['ID']
Y_data = df.pop('Fraud')
Y_data = Y_data.values
x_df = pd.get_dummies(df)
x_df.head(10).T

0  1  2  3  4  5  6  7  8  9
History_arrears          0  0  0  0  1  1  0  1  0  0
History_current          1  0  0  0  0  0  1  0  1  0
History_none             0  0  0  0  0  0  0  0  0  1
History_paid             0  1  1  1  0  0  0  0  0  0
CoApplicant_coapplicant  0  0  0  0  0  0  0  0  0  0
CoApplicant_guarantor    0  0  0  1  0  0  0  0  0  0
CoApplicant_none         1  1  1  0  1  1  1  1  1  1
Accommodation_free       0  0  0  0  0  0  0  0  0  0
Accommodation_own        1  1  1  0  1  1  1  1  0  1
Accommodation_rent       0  0  0  1  0  0  0  0  1  0

In [24]:
df

History  CoApplicant Accommodation
0   current         none           own
1      paid         none           own
2      paid         none           own
3      paid    guarantor          rent
4   arrears         none           own
5   arrears         none           own
6   current         none           own
7   arrears         none           own
8   current         none          rent
9      none         none           own
10  current  coapplicant           own
11  current         none           own
12  current         none          rent
13     paid         none           own
14  arrears         none           own
15  current         none           own
16  arrears  coapplicant          rent
17  arrears         none          free
18  arrears         none           own
19     paid         none           own

In [25]:
x_data = x_df.values
x_data

array([[0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0]], dtype=uint8)

In [26]:
P_Y_True = sum(Y_data == True) / len(Y_data)
P_Y_False = 1 - P_Y_True

P_Y_True, P_Y_False

(0.3, 0.7)

In [27]:
np.where(Y_data)

(array([ 0,  3,  5,  9, 11, 12]),)

In [29]:
ix_Y_True = np.where(Y_data)
ix_Y_False = np.where(Y_data==False)

ix_Y_True, ix_Y_False

((array([ 0,  3,  5,  9, 11, 12]),),
 (array([ 1,  2,  4,  6,  7,  8, 10, 13, 14, 15, 16, 17, 18, 19]),))

In [30]:
p_x_y_true = (x_data[ix_Y_True].sum(axis=0)) / sum(Y_data==True)
p_x_y_false = (x_data[ix_Y_False].sum(axis=0)) / sum(Y_data==False)

p_x_y_true, p_x_y_false

(array([0.16666667, 0.5       , 0.16666667, 0.16666667, 0.        ,
        0.16666667, 0.83333333, 0.        , 0.66666667, 0.33333333]),
 array([0.42857143, 0.28571429, 0.        , 0.28571429, 0.14285714,
        0.        , 0.85714286, 0.07142857, 0.78571429, 0.14285714]))

In [31]:
x_test = [0, 1, 0, 0, 0, 1, 0, 0, 1, 0]

p_y_true_test = P_Y_True + p_x_y_true.dot(x_test)
p_y_false_test = P_Y_False + p_x_y_false.dot(x_test)

p_y_true_test, p_y_false_test

(1.6333333333333333, 1.7714285714285714)

In [32]:
p_y_true_test < p_y_false_test

True

#### NAIVE BAYES with SCIKITLEARN

In [35]:
y_example_test = ['Sports', 'Not sports', 'Sports', 'Sports', 'Not Sports']
y_example = [1 if c=='Sports' else 0 for c in y_example_test ]
text_example = ['A great game game', 'The The election was over',
                'Very clean game match',
                'A clean but forgettable game game',
                'It was a close election', ]

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

countvect_example = CountVectorizer()
X_example = countvect_example.fit_transform(text_example)
countvect_example.get_feature_names_out()

array(['but', 'clean', 'close', 'election', 'forgettable', 'game',
       'great', 'it', 'match', 'over', 'the', 'very', 'was'], dtype=object)

In [41]:
countvect_example.transform(text_example).toarray()

array([[0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1]])

In [43]:
countvect_example.vocabulary_

{'great': 6,
 'game': 5,
 'the': 10,
 'election': 3,
 'was': 12,
 'over': 9,
 'very': 11,
 'clean': 1,
 'match': 8,
 'but': 0,
 'forgettable': 4,
 'it': 7,
 'close': 2}

In [44]:
from sklearn.naive_bayes import BernoulliNB

clf = BernoulliNB(alpha=1, binarize=0)
clf.fit(X_example, y_example)

BernoulliNB(alpha=1, binarize=0)

In [45]:
clf.class_log_prior_

array([-0.91629073, -0.51082562])

In [46]:
y_example

[1, 0, 1, 1, 0]

In [47]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB(alpha=1)
clf.fit(X_example, y_example)

MultinomialNB(alpha=1)

In [48]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(X_example.toarray(), y_example)

GaussianNB()

### Classifying Exercise

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import re 
%matplotlib inline

In [50]:
from sklearn.datasets import fetch_20newsgroups
news = fetch_20newsgroups(subset='all')
news.keys()

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

In [51]:
print(news.data[0])

From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>
Subject: Pens fans reactions
Organization: Post Office, Carnegie Mellon, Pittsburgh, PA
Lines: 12
NNTP-Posting-Host: po4.andrew.cmu.edu



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!




In [52]:
news.target

array([10,  3, 17, ...,  3,  1,  7])

In [53]:
news.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [55]:
news_df = pd.DataFrame({'News': news.data, 'Target': news.target})
news_df.head()

News  Target
0  From: Mamatha Devineni Ratnam <mr47+@andrew.cm...      10
1  From: mblawson@midway.ecn.uoknor.edu (Matthew ...       3
2  From: hilmi-er@dsv.su.se (Hilmi Eren)\nSubject...      17
3  From: guyd@austin.ibm.com (Guy Dawson)\nSubjec...       3
4  From: Alexander Samuel McDiarmid <am2o+@andrew...       4

In [56]:
target_dict = {idx:name for idx, name in enumerate(news.target_names)}
news_df['Target'] = news_df['Target'].replace(target_dict)

In [57]:
def data_cleansing(df):
    delete_email = re.sub(r'\b[\w\+]+@[\w]+.[\w]+.[\w]+.[\w]+\b', ' ', df)
    delete_number = re.sub(r'\b|\d+|\b', ' ', delete_email)
    delete_non_word = re.sub(r'\b[\W]+\b', ' ', delete_number)
    cleaning_result = ' '.join(delete_non_word.split())
    return cleaning_result

news_df.loc[:, 'News'] = news_df['News'].apply(data_cleansing)
news_df.head()

News                    Target
0  From Mamatha Devineni Ratnam Subject Pens fans...          rec.sport.hockey
1  From Matthew B Lawson Subject Which high perfo...  comp.sys.ibm.pc.hardware
2  From hilmi Hilmi Eren Subject Re ARMENIA SAYS ...     talk.politics.mideast
3  From Guy Dawson Subject Re IDE vs SCSI DMA and...  comp.sys.ibm.pc.hardware
4  From Alexander Samuel McDiarmid Subject driver...     comp.sys.mac.hardware

#### Vectorize

In [59]:
from nltk import stem
stmmer = stem.SnowballStemmer('english')
sentence = 'looking looks looked'
[stmmer.stem(word) for word in sentence.split()]

['look', 'look', 'look']

In [60]:
stmmer.stem('images'), stmmer.stem('imaging'), stmmer.stem('imagination')

('imag', 'imag', 'imagin')

In [61]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk

english_stemmer = nltk.stem.SnowballStemmer('english')
class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))
    
from sklearn.feature_extraction.text import TfidfVectorizer


In [63]:
english_stemmer = nltk.stem.SnowballStemmer('english')
class StemmedTfidVectorizer(TfidfVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedTfidVectorizer, self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

In [64]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline

vectorizer = [CountVectorizer(), TfidfVectorizer(), StemmedCountVectorizer(), StemmedTfidVectorizer()]

algorithms = [MultinomialNB(), LogisticRegression()]

pipelines = []

In [65]:
import itertools
for case in list(itertools.product(vectorizer, algorithms)):
    pipelines.append(make_pipeline(*case))

In [66]:
ngrams_params = [(1, 1), (1, 3)]
stopword_params = ['english']
lowercase_params = [True, False]
max_df_params = np.linspace(0.4, 0.6, num=6)
min_df_params = np.linspace(0.0, 0.0, num=1)

attributes = {"ngram_range": ngrams_params, "max_df": max_df_params, "min_df": min_df_params,
              "lowercase":lowercase_params, "stop_words":stopword_params}
vectorizer_names = ['countvectorizer', 'tfidfvectorizer', 'stemmedcount vectorizer', 'stemmedtfidfvectorizer']
vectorizer_params_dict = {}

for vect_name in vectorizer_names:
    vectorizer_params_dict[vect_name] = {}
    for key, value in attributes.items():
        param_name = vect_name + "__" + key
        vectorizer_params_dict[vect_name][param_name] = value

In [69]:
algorithm_names = ['multinomialnb', 'logisticregression']

algorithm_params_dict = {}
alpha_params = np.linspace(1.0, 1.0, num=1)
for i in range(1):
    algorithm_params_dict[algorithm_names[i]] = {
        algorithm_names[i]+"__alpha" : alpha_params
    }

c_params = [0.1, 5.0, 7.0, 10.0, 15.0, 20.0, 100.0]

algorithm_params_dict[algorithm_names[1]] = [{
    'logisticregression__multi_class': ['multinomial'],
    'logisticregression__solver': ['saga'],
    'logisticregression__penalty': ['l1'],
    'logisticregression__C': c_params},
    {'logisticregression__multi_class': ['ovr'],
    'logisticregression__solver': ['liblinear'],
    'logisticregression__penalty': ['l2'],
    'logisticregression__C': c_params}]

In [70]:
pipeline_params = []
for case in list(itertools.product(vectorizer_names, algorithm_names)):
    vect_params = vectorizer_params_dict[case[0]].copy()
    algo_params = algorithm_params_dict[case[1]]
    
    if isinstance(algo_params, dict):
        vect_params.update(algo_params)
        pipeline_params.append(vect_params)
        
    else:
        temp = []
        for param in algo_params:
            vect_params.update(param)
            temp.append(vect_params)
        pipeline_params.append(temp)
        

#### 학습 수행하기

In [71]:
from sklearn.preprocessing import LabelEncoder

X_data = news_df.loc[:, 'News'].tolist()
y_data = news_df['Target'].tolist()
y = LabelEncoder().fit_transform(y_data)

In [72]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score

scoring = ['accuracy']
estimator_results = []
for i, (estimator, params) in enumerate(zip(pipelines, pipeline_params)):
    n_jobs = -1
    gs_estimator = GridSearchCV(
        refit="accuracy", estimator=estimator, param_grid=params,
        scoring=scoring, cv=5, verbose=1, n_jobs=n_jobs)
    print(gs_estimator)
    
    gs_estimator.fit(X_data, y)
    estimator_results.append(gs_estimator)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('countvectorizer', CountVectorizer()),
                                       ('multinomialnb', MultinomialNB())]),
             n_jobs=-1,
             param_grid={'countvectorizer__lowercase': [True, False],
                         'countvectorizer__max_df': array([0.4 , 0.44, 0.48, 0.52, 0.56, 0.6 ]),
                         'countvectorizer__min_df': array([0.]),
                         'countvectorizer__ngram_range': [(1, 1), (1, 3)],
                         'countvectorizer__stop_words': ['english'],
                         'multinomialnb__alpha': array([1.])},
             refit='accuracy', scoring=['accuracy'], verbose=1)
Fitting 5 folds for each of 24 candidates, totalling 120 fits


/Users/seunghoonyang/opt/anaconda3/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py:702: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('countvectorizer', CountVectorizer()),
                                       ('logisticregression',
                                        LogisticRegression())]),
             n_jobs=-1,
             param_grid=[{'countvectorizer__lowercase': [True, False],
                          'countvectorizer__max_df': array([0.4 , 0.44, 0.48, 0.52, 0.56, 0.6 ]),
                          'countvectorizer__min_df': array([0.]),
                          'countvectorizer__ngram_range': [(1, 1), (1, 3)],
                          'countvecto...
                          'countvectorizer__min_df': array([0.]),
                          'countvectorizer__ngram_range': [(1, 1), (1, 3)],
                          'countvectorizer__stop_words': ['english'],
                          'logisticregression__C': [0.1, 5.0, 7.0, 10.0, 15.0,
                                                    20.0, 100.0],
                          'logisticregress

/Users/seunghoonyang/opt/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/seunghoonyang/opt/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/seunghoonyang/opt/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/seunghoonyang/opt/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/seunghoonyang/opt/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/seunghoonyang/opt/anaconda3/lib/p