In [1]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)

In [2]:
test_array

array([1., 4., 5., 8.])

In [3]:
test_list = [[1, 4, 5, 8], [1, 4, 5]]

In [4]:
np.array(test_list, float)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [5]:
test_array = np.array([1, 4, 5, 8], float)

In [6]:
type(test_array)

numpy.ndarray

In [7]:
type(test_array[3])

numpy.float64

### 3. 배열의 생성

In [8]:
test_array = np.array([1, 4, 5, "8"], float)

In [9]:
test_array

array([1., 4., 5., 8.])

In [10]:
print(test_array)

[1. 4. 5. 8.]


In [11]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [13]:
print(test_array.dtype)

float64


In [14]:
print(test_array.shape)

(4,)


In [15]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [16]:
tensor_rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [17]:
tensor_rank3 = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]
np.array(tensor_rank3, int).ndim

3

In [18]:
np.array(tensor_rank3, int).size

48

In [20]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [22]:
import sys
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float64).itemsize

8

In [23]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float32).itemsize

4

### 4. 배열의 구조 다루기

In [24]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [25]:
x.reshape(-1)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [26]:
x = np.array(range(8))

In [27]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [28]:
x.reshape(2, 2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [29]:
x.reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
x = np.array(range(8)).reshape(4, 2)

In [32]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [33]:
x.reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
x.reshape(2, 2, -1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
x = np.array(range(8)).reshape(2, 2, 2)

In [37]:
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

### 5. 인덱싱과 슬라이싱

#### 5.1 인덱싱

In [39]:
x = np.array([[1, 2, 3], [4.5, 5, 6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
x[0][0]

1

In [41]:
x[0, 2]

3

In [42]:
x[0, 1] = 100

In [43]:
x

array([[  1, 100,   3],
       [  4,   5,   6]])

#### 5.2 Slicing

In [44]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
x[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [45]:
x[1, 1:3]

array([7, 8])

In [46]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [47]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
x[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [49]:
x[::2, ::3]

array([[ 0,  3],
       [10, 13]])

### 6. 배열 생성 함수

#### 6.1 arange

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [52]:
range(10)

range(0, 10)

In [53]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [54]:
for i in np.arange(-5, 5):
    print(i)

-5
-4
-3
-2
-1
0
1
2
3
4


In [55]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [56]:
range(0, 5)

range(0, 5)

In [57]:
for i in range(0, 5):
    print(i)

0
1
2
3
4


In [58]:
for i in range(0, 5, 0.5):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

#### 6.2 ones, zeros, empty

In [59]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [60]:
np.zeros(shape=(2, 2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [61]:
np.empty(shape=(2, 4), dtype=np.float32)

array([[0.    , 1.875 , 0.    , 2.25  ],
       [0.    , 2.3125, 0.    , 2.5   ]], dtype=float32)

#### 6.3 ones_like, zeros_like, empty_like

In [62]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [64]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### 6.4 identity, eye, diag

In [65]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [66]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [67]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [68]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
np.diag(matrix)

array([0, 4, 8])

In [71]:
np.diag(matrix, k=1)

array([1, 5])

### 7. 통계 분석 함수

In [72]:
np.random.uniform(0, 5, 10)

array([0.2173874 , 1.34138275, 1.23734627, 3.96210687, 0.28452817,
       1.86089442, 4.7904908 , 1.69182625, 2.64200372, 2.25013931])

In [74]:
np.random.normal(0, 2, 10)

array([-0.18806934,  1.19033274, -0.70539613, -1.54397739,  1.62900588,
        2.77792906,  0.93622484, -0.27884868,  6.55057198, -1.27880223])

## 3. 넘파이 배열 연산

In [1]:
import numpy as np
test_array = np.arange(1, 11)
test_array.sum()

55

In [2]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [4]:
test_array.sum(axis=1)

array([10, 26, 42])

In [5]:
test_array = np.arange(1, 13).reshape(3, 4)
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [6]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [7]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [8]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [9]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [11]:
test_array.std()

3.452052529534663

In [12]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [13]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

### 2. 연결 함수

In [15]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.hstack((v1, v2))

array([1, 2, 3, 4, 5, 6])

In [21]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)

In [22]:
v1

array([[1],
       [2],
       [3]])

In [23]:
v2

array([[4],
       [5],
       [6]])

In [24]:
np.hstack((v1, v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])
np.concatenate((v1, v2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
v1 = np.array([1, 2, 3, 4]).reshape(2, 2)
v2 = np.array([[5, 6]]).T
v1

array([[1, 2],
       [3, 4]])

In [28]:
v2

array([[5],
       [6]])

In [29]:
np.concatenate((v1, v2), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### 3. 사칙연산 함수

In [30]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
x * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [33]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [34]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [36]:
x_1 = np.arange(1, 7).reshape(2, 3)
x_2 = np.arange(1, 7).reshape(3, 2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [39]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [41]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [42]:
x // 3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])

In [43]:
x ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [47]:
x % 3

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]])

In [48]:
x = np.arange(1, 13).reshape(4, 3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
v = np.arange(10, 40, 10)
v

array([10, 20, 30])

In [51]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [54]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result
iteration_max = 100000000

vector  = list(range(iteration_max))
scalar = 2

In [55]:
# for문을 이용한 성능
%timeit scalar_vector_product(scalar, vector)

10.6 s ± 192 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
# 리스트 컴프리헨션을 이용한 성능
%timeit [scalar * value for value in range(iteration_max)]

9.52 s ± 251 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [57]:
# 넘파이를 이용한 성능
%timeit np.arange(iteration_max) * scalar

491 ms ± 3.29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 4. 비교 연산과 데이터 추출

In [58]:
import numpy as np
x = np.array([4, 3, 2, 6, 8, 5])
x > 3

array([ True, False, False,  True,  True,  True])

In [59]:
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])
x > y

array([False,  True, False])

In [60]:
x = np.array([4, 6, 7, 3, 2])
(x > 3)

array([ True,  True,  True, False, False])

In [61]:
(x > 3).all()

False

In [62]:
(x > 3).any()

True

In [63]:
(x < 10).any()

True

In [64]:
(x < 10).all()

True

In [65]:
(x > 10).any()

False

In [67]:
x = np.array([4, 6, 7, 3, 2])
x > 5

array([False,  True,  True, False, False])

In [68]:
np.where(x>5)

(array([1, 2]),)

In [71]:
x = np.array([4, 6, 7, 3, 2])
np.where(x>5, 10, 20)

array([20, 10, 10, 20, 20])

In [72]:
x = np.array([4, 6, 7, 3, 2])
np.argsort(x)

array([4, 3, 0, 1, 2])

In [73]:
np.argmax(x)

2

In [74]:
np.argmin(x)

4

### 3. 인덱스를 활용한 데이터 추출

In [75]:
x = np.array([4, 6, 7, 3, 2])
x

array([4, 6, 7, 3, 2])

In [76]:
cond = x > 3
x[cond]

array([4, 6, 7])

In [77]:
x.shape

(5,)

In [78]:
cond.shape

(5,)

In [79]:
x = np.array([4, 6, 7, 3, 2])
cond = np.array([1, 2, 0, 2, 2, 2,], int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [80]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [81]:
x = np.array([[1, 4], [9, 16]], int)
a = np.array([0, 1, 1, 1, 0, 0], int)
b = np.array([0, 0, 0, 1, 1, 1], int)
x[a, b]

array([ 1,  9,  9, 16,  4,  4])