### SPAM FILTER

In [5]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

viagra_spam = {'viagra': [1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1],
               'spam': [1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]}

df = pd.DataFrame(viagra_spam)
np_data = df.values

In [6]:
df

viagra  spam
0        1     1
1        0     0
2        0     0
3        0     0
4        0     0
5        0     0
6        0     1
7        0     0
8        1     1
9        1     0
10       1     0
11       0     0
12       0     0
13       1     0
14       0     0
15       0     0
16       0     0
17       0     1
18       0     1
19       1     1

In [7]:
sum((np_data[:, 0] == 1) & (np_data[:, 1] == 1)) / 20

0.15

In [8]:
p_viagra = sum(np_data[:, 0] == 1) / len(np_data)
p_viagra

0.3

In [10]:
p_spam = sum(np_data[:, 1] == 1) / len(np_data)
p_spam

0.3

In [11]:
p_v_cap_s = sum((np_data[:, 0] == 1) & (np_data[:, 1] == 1)) / len(np_data)

In [12]:
p_n_v_cap_s = sum((np_data[:, 0] == 0) & (np_data[:, 1] == 1)) / len(np_data)
p_n_v_cap_s

0.15

In [13]:
p_spam * (p_v_cap_s / p_spam) / p_viagra

0.5

In [14]:
p_spam * (p_n_v_cap_s / p_spam) / (1-p_viagra)

0.2142857142857143

### NAIVE BAYESIAN CLASSIFIER

In [19]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

data_url = '../datasets/ch11/fraud.csv'
df = pd.read_csv(data_url, sep=',')
df.head()

ID  History CoApplicant Accommodation  Fraud
0   1  current        none           own   True
1   2     paid        none           own  False
2   3     paid        none           own  False
3   4     paid   guarantor          rent   True
4   5  arrears        none           own  False

In [20]:
df

ID  History  CoApplicant Accommodation  Fraud
0    1  current         none           own   True
1    2     paid         none           own  False
2    3     paid         none           own  False
3    4     paid    guarantor          rent   True
4    5  arrears         none           own  False
5    6  arrears         none           own   True
6    7  current         none           own  False
7    8  arrears         none           own  False
8    9  current         none          rent  False
9   10     none         none           own   True
10  11  current  coapplicant           own  False
11  12  current         none           own   True
12  13  current         none          rent   True
13  14     paid         none           own  False
14  15  arrears         none           own  False
15  16  current         none           own  False
16  17  arrears  coapplicant          rent  False
17  18  arrears         none          free  False
18  19  arrears         none           own  False
19  20     paid         none           own  False

In [21]:
del df['ID']
Y_data = df.pop('Fraud')
Y_data = Y_data.values
x_df = pd.get_dummies(df)
x_df.head(10).T

0  1  2  3  4  5  6  7  8  9
History_arrears          0  0  0  0  1  1  0  1  0  0
History_current          1  0  0  0  0  0  1  0  1  0
History_none             0  0  0  0  0  0  0  0  0  1
History_paid             0  1  1  1  0  0  0  0  0  0
CoApplicant_coapplicant  0  0  0  0  0  0  0  0  0  0
CoApplicant_guarantor    0  0  0  1  0  0  0  0  0  0
CoApplicant_none         1  1  1  0  1  1  1  1  1  1
Accommodation_free       0  0  0  0  0  0  0  0  0  0
Accommodation_own        1  1  1  0  1  1  1  1  0  1
Accommodation_rent       0  0  0  1  0  0  0  0  1  0

In [24]:
df

History  CoApplicant Accommodation
0   current         none           own
1      paid         none           own
2      paid         none           own
3      paid    guarantor          rent
4   arrears         none           own
5   arrears         none           own
6   current         none           own
7   arrears         none           own
8   current         none          rent
9      none         none           own
10  current  coapplicant           own
11  current         none           own
12  current         none          rent
13     paid         none           own
14  arrears         none           own
15  current         none           own
16  arrears  coapplicant          rent
17  arrears         none          free
18  arrears         none           own
19     paid         none           own

In [25]:
x_data = x_df.values
x_data

array([[0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 1, 0]], dtype=uint8)

In [26]:
P_Y_True = sum(Y_data == True) / len(Y_data)
P_Y_False = 1 - P_Y_True

P_Y_True, P_Y_False

(0.3, 0.7)

In [27]:
np.where(Y_data)

(array([ 0,  3,  5,  9, 11, 12]),)

In [29]:
ix_Y_True = np.where(Y_data)
ix_Y_False = np.where(Y_data==False)

ix_Y_True, ix_Y_False

((array([ 0,  3,  5,  9, 11, 12]),),
 (array([ 1,  2,  4,  6,  7,  8, 10, 13, 14, 15, 16, 17, 18, 19]),))

In [30]:
p_x_y_true = (x_data[ix_Y_True].sum(axis=0)) / sum(Y_data==True)
p_x_y_false = (x_data[ix_Y_False].sum(axis=0)) / sum(Y_data==False)

p_x_y_true, p_x_y_false

(array([0.16666667, 0.5       , 0.16666667, 0.16666667, 0.        ,
        0.16666667, 0.83333333, 0.        , 0.66666667, 0.33333333]),
 array([0.42857143, 0.28571429, 0.        , 0.28571429, 0.14285714,
        0.        , 0.85714286, 0.07142857, 0.78571429, 0.14285714]))

In [31]:
x_test = [0, 1, 0, 0, 0, 1, 0, 0, 1, 0]

p_y_true_test = P_Y_True + p_x_y_true.dot(x_test)
p_y_false_test = P_Y_False + p_x_y_false.dot(x_test)

p_y_true_test, p_y_false_test

(1.6333333333333333, 1.7714285714285714)

In [32]:
p_y_true_test < p_y_false_test

True

#### NAIVE BAYES with SCIKITLEARN

In [35]:
y_example_test = ['Sports', 'Not sports', 'Sports', 'Sports', 'Not Sports']
y_example = [1 if c=='Sports' else 0 for c in y_example_test ]
text_example = ['A great game game', 'The The election was over',
                'Very clean game match',
                'A clean but forgettable game game',
                'It was a close election', ]

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

countvect_example = CountVectorizer()
X_example = countvect_example.fit_transform(text_example)
countvect_example.get_feature_names_out()

array(['but', 'clean', 'close', 'election', 'forgettable', 'game',
       'great', 'it', 'match', 'over', 'the', 'very', 'was'], dtype=object)

In [41]:
countvect_example.transform(text_example).toarray()

array([[0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1]])

In [43]:
countvect_example.vocabulary_

{'great': 6,
 'game': 5,
 'the': 10,
 'election': 3,
 'was': 12,
 'over': 9,
 'very': 11,
 'clean': 1,
 'match': 8,
 'but': 0,
 'forgettable': 4,
 'it': 7,
 'close': 2}

In [44]:
from sklearn.naive_bayes import BernoulliNB

clf = BernoulliNB(alpha=1, binarize=0)
clf.fit(X_example, y_example)

BernoulliNB(alpha=1, binarize=0)

In [45]:
clf.class_log_prior_

array([-0.91629073, -0.51082562])

In [46]:
y_example

[1, 0, 1, 1, 0]

In [47]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB(alpha=1)
clf.fit(X_example, y_example)

MultinomialNB(alpha=1)

In [48]:
from sklearn.naive_bayes import GaussianNB

clf = GaussianNB()
clf.fit(X_example.toarray(), y_example)

GaussianNB()

### Classifying Exercise