In [1]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)

In [2]:
test_array

array([1., 4., 5., 8.])

In [3]:
test_list = [[1, 4, 5, 8], [1, 4, 5]]

In [4]:
np.array(test_list, float)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [5]:
test_array = np.array([1, 4, 5, 8], float)

In [6]:
type(test_array)

numpy.ndarray

In [7]:
type(test_array[3])

numpy.float64

### 3. 배열의 생성

In [8]:
test_array = np.array([1, 4, 5, "8"], float)

In [9]:
test_array

array([1., 4., 5., 8.])

In [10]:
print(test_array)

[1. 4. 5. 8.]


In [11]:
print(type(test_array[3]))

<class 'numpy.float64'>


In [13]:
print(test_array.dtype)

float64


In [14]:
print(test_array.shape)

(4,)


In [15]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [16]:
tensor_rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [17]:
tensor_rank3 = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
                [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]]
np.array(tensor_rank3, int).ndim

3

In [18]:
np.array(tensor_rank3, int).size

48

In [20]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [22]:
import sys
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float64).itemsize

8

In [23]:
np.array([[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float32).itemsize

4

### 4. 배열의 구조 다루기

In [24]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [25]:
x.reshape(-1)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [26]:
x = np.array(range(8))

In [27]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [28]:
x.reshape(2, 2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [29]:
x.reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
x = np.array(range(8)).reshape(4, 2)

In [32]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [33]:
x.reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
x.reshape(2, 2, -1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
x = np.array(range(8)).reshape(2, 2, 2)

In [37]:
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

### 5. 인덱싱과 슬라이싱